global:
  scrape_interval: 15s # De quanto em quanto tempo vai coletar

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Monitorando o próprio host
